detections:
  colors:
    label:
      hue:
        max: 255
        min: 0
      sat:
        max: 255
        min: 66
      val:
        max: 255
        min: 100
    liquid:
      hue:
        max: 162
        min: 0
      sat:
        max: 43
        min: 0
      val:
        max: 255
        min: 190
  debugging_mode: false
  evaluation:
    label:
      bottom_position: 50
      deviation: 0.1
      height: 20
      top_position: 30
    liquid:
      deviation: 0.05
      fill: 80
  tf:
    threshold: 0.25
    version: 4.0
